apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: legomcp-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: legomcp
    app.kubernetes.io/instance: staging
    app.kubernetes.io/component: application
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: legomcp

  source:
    repoURL: https://github.com/your-org/lego-mcp-fusion360.git
    targetRevision: release
    path: helm/legomcp

    helm:
      releaseName: legomcp-staging
      valueFiles:
        - values.yaml
        - values-staging.yaml

      values: |
        environment: staging

        dashboard:
          replicaCount: 2
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi

        worker:
          replicaCount: 2
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi

        mlWorker:
          enabled: true
          replicaCount: 1
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
              nvidia.com/gpu: 1
            requests:
              cpu: 500m
              memory: 2Gi

        scheduler:
          replicaCount: 1

        postgresql:
          enabled: true
          primary:
            persistence:
              size: 20Gi

        redis:
          enabled: true
          master:
            persistence:
              size: 5Gi

        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-staging
          hosts:
            - host: legomcp-staging.example.com
              paths:
                - path: /
                  pathType: Prefix

        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 5

        monitoring:
          enabled: true
          serviceMonitor:
            enabled: true

        backup:
          enabled: true
          schedule: "0 2 * * *"

  destination:
    server: https://kubernetes.default.svc
    namespace: legomcp-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
