apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: legomcp-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: legomcp
    app.kubernetes.io/instance: dev
    app.kubernetes.io/component: application
    environment: dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: legomcp

  source:
    repoURL: https://github.com/your-org/lego-mcp-fusion360.git
    targetRevision: develop
    path: helm/legomcp

    helm:
      releaseName: legomcp-dev
      valueFiles:
        - values.yaml
        - values-dev.yaml

      # Override values for dev environment
      values: |
        environment: development

        dashboard:
          replicaCount: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

        worker:
          replicaCount: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

        mlWorker:
          enabled: false

        scheduler:
          replicaCount: 1

        postgresql:
          enabled: true
          primary:
            persistence:
              size: 5Gi

        redis:
          enabled: true
          master:
            persistence:
              size: 1Gi

        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-staging
          hosts:
            - host: legomcp-dev.example.com
              paths:
                - path: /
                  pathType: Prefix

        autoscaling:
          enabled: false

        monitoring:
          enabled: true
          serviceMonitor:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: legomcp-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health checks
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/minReplicas
        - /spec/maxReplicas

  # Notifications (requires argocd-notifications)
  # notifications:
  #   triggers:
  #     - on-sync-succeeded
  #     - on-sync-failed
  #     - on-health-degraded
