apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: legomcp-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: legomcp
    app.kubernetes.io/instance: prod
    app.kubernetes.io/component: application
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    # Require manual sync for production
    argocd.argoproj.io/sync-options: Validate=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: legomcp

  source:
    repoURL: https://github.com/your-org/lego-mcp-fusion360.git
    targetRevision: main
    path: helm/legomcp

    helm:
      releaseName: legomcp-prod
      valueFiles:
        - values.yaml
        - values-prod.yaml

      values: |
        environment: production

        dashboard:
          replicaCount: 3
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi

          # Pod anti-affinity for HA
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/component
                        operator: In
                        values:
                          - dashboard
                  topologyKey: kubernetes.io/hostname

        worker:
          replicaCount: 3
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi

        mlWorker:
          enabled: true
          replicaCount: 2
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
              nvidia.com/gpu: 1
            requests:
              cpu: 1000m
              memory: 4Gi

        scheduler:
          replicaCount: 2

        # External databases for production
        postgresql:
          enabled: false

        externalPostgresql:
          host: legomcp-prod.cluster-xyz.us-west-2.rds.amazonaws.com
          port: 5432
          database: legomcp
          existingSecret: legomcp-postgres-secret

        redis:
          enabled: false

        externalRedis:
          host: legomcp-prod.xyz.ng.0001.usw2.cache.amazonaws.com
          port: 6379
          existingSecret: legomcp-redis-secret

        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/rate-limit: "100"
            nginx.ingress.kubernetes.io/limit-connections: "10"
          hosts:
            - host: legomcp.example.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: legomcp-prod-tls
              hosts:
                - legomcp.example.com

        autoscaling:
          enabled: true
          minReplicas: 3
          maxReplicas: 10
          targetCPUUtilizationPercentage: 70
          targetMemoryUtilizationPercentage: 80

        podDisruptionBudget:
          enabled: true
          minAvailable: 2

        monitoring:
          enabled: true
          serviceMonitor:
            enabled: true
          alerts:
            enabled: true

        backup:
          enabled: true
          schedule: "0 */6 * * *"
          retention: 30

        secrets:
          externalSecrets:
            enabled: true
            secretStore:
              kind: ClusterSecretStore
              name: aws-secrets-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: legomcp-prod

  # Manual sync for production (no automated)
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Validate=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/minReplicas
        - /spec/maxReplicas

  # Revision history limit
  revisionHistoryLimit: 10
